### ISSUE TITLE
附录

### ISSUE THREAD

**Issue by M-SunRise** [ICTMCG/DNA-Det#1]
在文中提到的附录，我可以在哪里获得？

**Comment by Maikuki** [comment]
We have updated the version on arxiv with an appendix. Please check out here: https://arxiv.org/pdf/2202.13843.pdf

**Comment by TianyunYoung** [comment]
@M-SunRise We have updated the version on arxiv with an appendix. Please check out here: https://arxiv.org/pdf/2202.13843.pdf
