### ISSUE TITLE
Not able to download the dataset

### ISSUE THREAD

**Issue by indrakumarmhaski** [ICTMCG/DNA-Det#2]
https://pan.baidu.com/s/1nCfkyflsZs-ECz7LiUngTQ

It requires signup on baidu.com and signup is not supported from outside china. Please upload the dataset on google drive and share the link. It'll be really helpful. Thanks!

**Comment by TianyunYoung** [comment]
@indrakumarmhaski  I have sent you an email with the google drive link, please check the email. Regards.

**Comment by indrakumarmhaski** [comment]
I got it.
Thanks!

**Comment by zjbthomas** [comment]
Hi @Maikuki, Could you please share the dataset again on Google Drive? Thank you!
